#include "main.h"
#include <stdio.h>
#include <string.h>
#include "audio_pipeline.h"
#include "audio.h"
#include "adc.h"   // <--- Crucial
#include "usart.h"

extern AudioPipeline_t myPipeline;
extern bool audio_ready;

/* --- Peripheral Handles (Generated by CubeMX) --- */
extern ADC_HandleTypeDef hadc1;
extern TIM_HandleTypeDef htim2;   /* 8kHz Timer */
extern UART_HandleTypeDef huart2; /* Debug Serial */

/* --- UART Debug Helper --- */
void UART_Log(const char* message) {
    HAL_UART_Transmit(&huart2, (uint8_t*)message, strlen(message), 10);
    HAL_UART_Transmit(&huart2, (uint8_t*)"\r\n", 2, 10);
}

/* --- Preset & Source Logic --- */
void Handle_Interface_Buttons(void) {
    static uint8_t last_preset = 255;
    static InputSource_t last_source = 255;
    char debug_buffer[50];

    // 1. Check Master Source Toggle (A4)
    InputSource_t current_source = (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_4) == GPIO_PIN_SET) ? SOURCE_MIC : SOURCE_CV;

    if (current_source != last_source) {
        myPipeline.source = current_source;
        last_source = current_source;
        UART_Log(current_source == SOURCE_MIC ? "[STATUS] Source: MICROPHONE" : "[STATUS] Source: VCO (CV)");
    }

    // 2. Check Preset Selectors (A0 - A3)
    uint8_t current_preset = myPipeline.active_preset;
    if      (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_SET) current_preset = 0;
    else if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_SET) current_preset = 1;
    else if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_2) == GPIO_PIN_SET) current_preset = 2;
    else if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_3) == GPIO_PIN_SET) current_preset = 3;

    if (current_preset != last_preset) {
        myPipeline.active_preset = current_preset;
        last_preset = current_preset;

        sprintf(debug_buffer, "[STATUS] Preset Changed to: %d", current_preset + 1);
        UART_Log(debug_buffer);
    }
}


/* --- Basic PWM Sine Test (440Hz @ 8kHz Sample Rate) --- */
void Run_Basic_PWM_Test(void) {
    // A simple 18-point sine table (normalized 0.0 to 1.0)
    float sine_table[18] = {
        0.50, 0.67, 0.82, 0.93, 0.99, 0.99, 0.93, 0.82, 0.67,
        0.50, 0.33, 0.18, 0.07, 0.01, 0.01, 0.07, 0.18, 0.33
    };
    static uint8_t index = 0;

    UART_Log("!!! STARTING BASIC PWM HARDWARE TEST (440Hz Sine) !!!");

    while (1) {
        if (audio_ready) {
            // 1. Get next value from table
            float val = sine_table[index];

            // 2. Convert to PWM (Assuming ARR = 1049)
            // Range: 0 to 1049
            uint32_t pwm_duty = (uint32_t)(val * 1049.0f);

            // 3. Update Timer
            __HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, pwm_duty);

            // 4. Increment and wrap index
            index = (index + 1) % 18;

            audio_ready = false;
        }
    }
}
/* --- Main Entry Point --- */
void Audio_Internal_Test(void) {
    HAL_Init();
    /* System Clock Config happens here via CubeMX */

    Pipeline_Init(&myPipeline);

    // Start Peripherals
    HAL_ADC_Start(&hadc1);
    HAL_TIM_Base_Start_IT(&htim2);       // Start 8kHz Interrupts

    UART_Log("--- ModBox Audio Coprocessor Online ---");

    uint32_t last_ui_tick = 0;

    while (1) {
        // Debounced button scanning (every 20ms)
//        if (HAL_GetTick() - last_ui_tick > 20) {
//            Handle_Interface_Buttons();
//            last_ui_tick = HAL_GetTick();
//        }
    	// Debug print every 1000ms
		static uint32_t last_print = 0;
		if (HAL_GetTick() - last_print > 1000) {
			char msg[50];
			sprintf(msg, "[DEBUG] Current Pipeline Preset: %d\r\n", myPipeline.active_preset);
			UART_Log(msg);
			last_print = HAL_GetTick();
		}
        // High-speed Audio Processing
    	// High-speed Audio Processing
			if (audio_ready) {
				// 1. Read hardware Gate (PC13 is active-low)
				bool gate_in = (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_RESET);

				// 2. Read Sample (from Analog VCO)
				// (Note: Since we are using UART, we assume source is handled by the pipeline now)
				int16_t adc_val = (int16_t)HAL_ADC_GetValue(&hadc1);

				// 3. Process signal through the DSP Pipeline
				float audio_out = Pipeline_Process(&myPipeline, adc_val, gate_in);

				// 4. Send to PWM (Using the 1049 Timer ARR math from earlier)
				uint32_t pwm_val = (uint32_t)((audio_out + 1.0f) * 525.0f);
				if (pwm_val > 1049) pwm_val = 1049; // Prevent timer overflow/popping

				__HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, pwm_val);

				// 5. Reset flag for the next cycle
				audio_ready = false;
			}
    }
}
