#include "main.h"
#include <stdio.h>
#include <string.h>
#include "audio_pipeline.h"
#include "audio.h"
#include "adc.h"   // <--- Crucial
#include "dac.h"   // <--- Crucial
#include "tim.h"   // <--- Crucial

AudioPipeline_t myPipeline;
volatile bool audio_ready = false;

/* --- Peripheral Handles (Generated by CubeMX) --- */
extern ADC_HandleTypeDef hadc1;
extern DAC_HandleTypeDef hdac;
extern TIM_HandleTypeDef htim2;   /* 8kHz Timer */
extern UART_HandleTypeDef huart2; /* Debug Serial */

/* --- UART Debug Helper --- */
void UART_Log(const char* message) {
    HAL_UART_Transmit(&huart2, (uint8_t*)message, strlen(message), 10);
    HAL_UART_Transmit(&huart2, (uint8_t*)"\r\n", 2, 10);
}

/* --- Preset & Source Logic --- */
void Handle_Interface_Buttons(void) {
    static uint8_t last_preset = 255;
    static InputSource_t last_source = 255;
    char debug_buffer[50];

    // 1. Check Master Source Toggle (A4)
    InputSource_t current_source = (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_4) == GPIO_PIN_SET) ? SOURCE_MIC : SOURCE_CV;

    if (current_source != last_source) {
        myPipeline.source = current_source;
        last_source = current_source;
        UART_Log(current_source == SOURCE_MIC ? "[STATUS] Source: MICROPHONE" : "[STATUS] Source: VCO (CV)");
    }

    // 2. Check Preset Selectors (A0 - A3)
    uint8_t current_preset = myPipeline.active_preset;
    if      (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_SET) current_preset = 0;
    else if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_SET) current_preset = 1;
    else if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_2) == GPIO_PIN_SET) current_preset = 2;
    else if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_3) == GPIO_PIN_SET) current_preset = 3;

    if (current_preset != last_preset) {
        myPipeline.active_preset = current_preset;
        last_preset = current_preset;

        sprintf(debug_buffer, "[STATUS] Preset Changed to: %d", current_preset + 1);
        UART_Log(debug_buffer);
    }
}

/* --- Main Entry Point --- */
int main(void) {
    HAL_Init();
    /* System Clock Config happens here via CubeMX */

    Pipeline_Init(&myPipeline);

    // Start Peripherals
    HAL_ADC_Start(&hadc1);
    HAL_DAC_Start(&hdac, DAC_CHANNEL_1); // Audio -> To VCF
    HAL_DAC_Start(&hdac, DAC_CHANNEL_2); // CV    -> To VCA
    HAL_TIM_Base_Start_IT(&htim2);       // Start 8kHz Interrupts

    UART_Log("--- ModBox Audio Coprocessor Online ---");

    uint32_t last_ui_tick = 0;

    while (1) {
        // Debounced button scanning (every 20ms)
        if (HAL_GetTick() - last_ui_tick > 20) {
            Handle_Interface_Buttons();
            last_ui_tick = HAL_GetTick();
        }

        // High-speed Audio Processing
        if (audio_ready) {
            // Read hardware Gate (PC13 is active-low)
            bool gate_in = (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_RESET);

            // Read Sample (from VCO or MIC depending on source)
            int16_t adc_val = (int16_t)HAL_ADC_GetValue(&hadc1);

            // Process signal through the 4-Preset Pipeline
            int16_t audio_out = Pipeline_Process(&myPipeline, adc_val, gate_in);

            // Update Hardware Outputs
            // DAC 1: Audio Signal centered for AC
            HAL_DAC_SetValue(&hdac, DAC_CHANNEL_1, DAC_ALIGN_12B_R, audio_out + 2048);

            // DAC 2: Envelope CV for the VCA (0 to 4095)
            HAL_DAC_SetValue(&hdac, DAC_CHANNEL_2, DAC_ALIGN_12B_R, myPipeline.envelope.output);

            audio_ready = false;
        }
    }
}

/* --- Timer Interrupt --- */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    if (htim->Instance == TIM2) {
        audio_ready = true;
    }
}
